/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreateProjectRequestDescription } from './createProjectRequestDescription';
import type { CreateProjectRequestUrl } from './createProjectRequestUrl';

export interface CreateProjectRequest {
  /** @minLength 1 */
  name: string;
  description?: CreateProjectRequestDescription;
  url?: CreateProjectRequestUrl;
}
