/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreateProfileRequestContactPhone } from './createProfileRequestContactPhone';
import type { CreateProfileRequestWorkLocation } from './createProfileRequestWorkLocation';
import type { CreateProfileRequestSummary } from './createProfileRequestSummary';

export interface CreateProfileRequest {
  /** @minLength 1 */
  first_name: string;
  /** @minLength 1 */
  last_name: string;
  contact_email: string;
  contact_phone?: CreateProfileRequestContactPhone;
  work_location?: CreateProfileRequestWorkLocation;
  summary?: CreateProfileRequestSummary;
}
