/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreateExperienceRequestDescription } from './createExperienceRequestDescription';
import type { CreateExperienceRequestEndDate } from './createExperienceRequestEndDate';

export interface CreateExperienceRequest {
  /** @minLength 1 */
  company: string;
  /** @minLength 1 */
  title: string;
  start_date: string;
  description?: CreateExperienceRequestDescription;
  end_date?: CreateExperienceRequestEndDate;
}
