/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface CreateLinkRequest {
  /** @minLength 1 */
  label: string;
  url: string;
}
