/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { JobListingDTO } from './jobListingDTO';
import type { JobApplicationDTOUsedResume } from './jobApplicationDTOUsedResume';
import type { JobApplicationDTOUsedCoverLetter } from './jobApplicationDTOUsedCoverLetter';
import type { JobApplicationDTONotes } from './jobApplicationDTONotes';

export interface JobApplicationDTO {
  id: number;
  job_listing: JobListingDTO;
  used_resume: JobApplicationDTOUsedResume;
  used_cover_letter: JobApplicationDTOUsedCoverLetter;
  notes: JobApplicationDTONotes;
}
