/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { StoredFileDTO } from './storedFileDTO';

export interface PresignedUrlDTO {
  file: StoredFileDTO;
  presigned_url: string;
}
