/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ProfileLinkDTO {
  id: number;
  label: string;
  url: string;
  created_at: string;
  updated_at: string;
}
