/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  BodyCreateProfileFromResume,
  CreateCertificationRequest,
  CreateEducationRequest,
  CreateExperienceRequest,
  CreateLinkRequest,
  CreateProfileRequest,
  CreateProjectRequest,
  CreateSkillRequest,
  ErrorModel,
  HTTPValidationError,
  ProfileCertificationDTO,
  ProfileDTO,
  ProfileEducationDTO,
  ProfileExperienceDTO,
  ProfileLinkDTO,
  ProfileProjectDTO,
  ProfileSkillDTO,
  UpdateCertificationRequest,
  UpdateEducationRequest,
  UpdateExperienceRequest,
  UpdateLinkRequest,
  UpdateProfileRequest,
  UpdateProjectRequest,
  UpdateSkillRequest
} from '.././models';





/**
 * @summary Get Profile
 */
export const getProfile = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileDTO>> => {
    
    
    return axios.default.get(
      `/profiles/`,options
    );
  }


export const getGetProfileQueryKey = () => {
    return [`/profiles/`] as const;
    }

    
export const getGetProfileQueryOptions = <TData = Awaited<ReturnType<typeof getProfile>>, TError = AxiosError<ErrorModel>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProfile>>> = ({ signal }) => getProfile({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getProfile>>>
export type GetProfileQueryError = AxiosError<ErrorModel>


export function useGetProfile<TData = Awaited<ReturnType<typeof getProfile>>, TError = AxiosError<ErrorModel>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProfile>>,
          TError,
          Awaited<ReturnType<typeof getProfile>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProfile<TData = Awaited<ReturnType<typeof getProfile>>, TError = AxiosError<ErrorModel>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProfile>>,
          TError,
          Awaited<ReturnType<typeof getProfile>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProfile<TData = Awaited<ReturnType<typeof getProfile>>, TError = AxiosError<ErrorModel>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Profile
 */

export function useGetProfile<TData = Awaited<ReturnType<typeof getProfile>>, TError = AxiosError<ErrorModel>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProfileQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create Profile
 */
export const createProfile = (
    createProfileRequest: CreateProfileRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileDTO>> => {
    
    
    return axios.default.post(
      `/profiles/`,
      createProfileRequest,options
    );
  }



export const getCreateProfileMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProfile>>, TError,{data: CreateProfileRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createProfile>>, TError,{data: CreateProfileRequest}, TContext> => {

const mutationKey = ['createProfile'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProfile>>, {data: CreateProfileRequest}> = (props) => {
          const {data} = props ?? {};

          return  createProfile(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProfileMutationResult = NonNullable<Awaited<ReturnType<typeof createProfile>>>
    export type CreateProfileMutationBody = CreateProfileRequest
    export type CreateProfileMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Create Profile
 */
export const useCreateProfile = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProfile>>, TError,{data: CreateProfileRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProfile>>,
        TError,
        {data: CreateProfileRequest},
        TContext
      > => {

      const mutationOptions = getCreateProfileMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Delete Profile
 */
export const deleteProfile = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.delete(
      `/profiles/`,options
    );
  }



export const getDeleteProfileMutationOptions = <TError = AxiosError<ErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProfile>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProfile>>, TError,void, TContext> => {

const mutationKey = ['deleteProfile'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProfile>>, void> = () => {
          

          return  deleteProfile(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProfileMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProfile>>>
    
    export type DeleteProfileMutationError = AxiosError<ErrorModel>

    /**
 * @summary Delete Profile
 */
export const useDeleteProfile = <TError = AxiosError<ErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProfile>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProfile>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getDeleteProfileMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Update Profile
 */
export const updateProfile = (
    updateProfileRequest: UpdateProfileRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileDTO>> => {
    
    
    return axios.default.patch(
      `/profiles/`,
      updateProfileRequest,options
    );
  }



export const getUpdateProfileMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProfile>>, TError,{data: UpdateProfileRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateProfile>>, TError,{data: UpdateProfileRequest}, TContext> => {

const mutationKey = ['updateProfile'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProfile>>, {data: UpdateProfileRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateProfile(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProfileMutationResult = NonNullable<Awaited<ReturnType<typeof updateProfile>>>
    export type UpdateProfileMutationBody = UpdateProfileRequest
    export type UpdateProfileMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Update Profile
 */
export const useUpdateProfile = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProfile>>, TError,{data: UpdateProfileRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProfile>>,
        TError,
        {data: UpdateProfileRequest},
        TContext
      > => {

      const mutationOptions = getUpdateProfileMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Create Profile From Resume
 */
export const createProfileFromResume = (
    bodyCreateProfileFromResume: BodyCreateProfileFromResume, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileDTO>> => {
    
    const formData = new FormData();
formData.append(`file`, bodyCreateProfileFromResume.file)

    return axios.default.post(
      `/profiles/create-from-resume`,
      formData,options
    );
  }



export const getCreateProfileFromResumeMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProfileFromResume>>, TError,{data: BodyCreateProfileFromResume}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createProfileFromResume>>, TError,{data: BodyCreateProfileFromResume}, TContext> => {

const mutationKey = ['createProfileFromResume'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProfileFromResume>>, {data: BodyCreateProfileFromResume}> = (props) => {
          const {data} = props ?? {};

          return  createProfileFromResume(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProfileFromResumeMutationResult = NonNullable<Awaited<ReturnType<typeof createProfileFromResume>>>
    export type CreateProfileFromResumeMutationBody = BodyCreateProfileFromResume
    export type CreateProfileFromResumeMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Create Profile From Resume
 */
export const useCreateProfileFromResume = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProfileFromResume>>, TError,{data: BodyCreateProfileFromResume}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProfileFromResume>>,
        TError,
        {data: BodyCreateProfileFromResume},
        TContext
      > => {

      const mutationOptions = getCreateProfileFromResumeMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Add Experience
 */
export const addExperience = (
    createExperienceRequest: CreateExperienceRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileExperienceDTO>> => {
    
    
    return axios.default.post(
      `/profiles/experiences`,
      createExperienceRequest,options
    );
  }



export const getAddExperienceMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addExperience>>, TError,{data: CreateExperienceRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addExperience>>, TError,{data: CreateExperienceRequest}, TContext> => {

const mutationKey = ['addExperience'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addExperience>>, {data: CreateExperienceRequest}> = (props) => {
          const {data} = props ?? {};

          return  addExperience(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddExperienceMutationResult = NonNullable<Awaited<ReturnType<typeof addExperience>>>
    export type AddExperienceMutationBody = CreateExperienceRequest
    export type AddExperienceMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Add Experience
 */
export const useAddExperience = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addExperience>>, TError,{data: CreateExperienceRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addExperience>>,
        TError,
        {data: CreateExperienceRequest},
        TContext
      > => {

      const mutationOptions = getAddExperienceMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Update Experience
 */
export const updateExperience = (
    experienceId: number,
    updateExperienceRequest: UpdateExperienceRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileExperienceDTO>> => {
    
    
    return axios.default.patch(
      `/profiles/experiences/${experienceId}`,
      updateExperienceRequest,options
    );
  }



export const getUpdateExperienceMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateExperience>>, TError,{experienceId: number;data: UpdateExperienceRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateExperience>>, TError,{experienceId: number;data: UpdateExperienceRequest}, TContext> => {

const mutationKey = ['updateExperience'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateExperience>>, {experienceId: number;data: UpdateExperienceRequest}> = (props) => {
          const {experienceId,data} = props ?? {};

          return  updateExperience(experienceId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateExperienceMutationResult = NonNullable<Awaited<ReturnType<typeof updateExperience>>>
    export type UpdateExperienceMutationBody = UpdateExperienceRequest
    export type UpdateExperienceMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Update Experience
 */
export const useUpdateExperience = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateExperience>>, TError,{experienceId: number;data: UpdateExperienceRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateExperience>>,
        TError,
        {experienceId: number;data: UpdateExperienceRequest},
        TContext
      > => {

      const mutationOptions = getUpdateExperienceMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Delete Experience
 */
export const deleteExperience = (
    experienceId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.delete(
      `/profiles/experiences/${experienceId}`,options
    );
  }



export const getDeleteExperienceMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteExperience>>, TError,{experienceId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteExperience>>, TError,{experienceId: number}, TContext> => {

const mutationKey = ['deleteExperience'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteExperience>>, {experienceId: number}> = (props) => {
          const {experienceId} = props ?? {};

          return  deleteExperience(experienceId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteExperienceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteExperience>>>
    
    export type DeleteExperienceMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Delete Experience
 */
export const useDeleteExperience = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteExperience>>, TError,{experienceId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteExperience>>,
        TError,
        {experienceId: number},
        TContext
      > => {

      const mutationOptions = getDeleteExperienceMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Add Education
 */
export const addEducation = (
    createEducationRequest: CreateEducationRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileEducationDTO>> => {
    
    
    return axios.default.post(
      `/profiles/educations`,
      createEducationRequest,options
    );
  }



export const getAddEducationMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addEducation>>, TError,{data: CreateEducationRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addEducation>>, TError,{data: CreateEducationRequest}, TContext> => {

const mutationKey = ['addEducation'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addEducation>>, {data: CreateEducationRequest}> = (props) => {
          const {data} = props ?? {};

          return  addEducation(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddEducationMutationResult = NonNullable<Awaited<ReturnType<typeof addEducation>>>
    export type AddEducationMutationBody = CreateEducationRequest
    export type AddEducationMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Add Education
 */
export const useAddEducation = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addEducation>>, TError,{data: CreateEducationRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addEducation>>,
        TError,
        {data: CreateEducationRequest},
        TContext
      > => {

      const mutationOptions = getAddEducationMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Update Education
 */
export const updateEducation = (
    educationId: number,
    updateEducationRequest: UpdateEducationRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileEducationDTO>> => {
    
    
    return axios.default.patch(
      `/profiles/educations/${educationId}`,
      updateEducationRequest,options
    );
  }



export const getUpdateEducationMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEducation>>, TError,{educationId: number;data: UpdateEducationRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateEducation>>, TError,{educationId: number;data: UpdateEducationRequest}, TContext> => {

const mutationKey = ['updateEducation'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateEducation>>, {educationId: number;data: UpdateEducationRequest}> = (props) => {
          const {educationId,data} = props ?? {};

          return  updateEducation(educationId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateEducationMutationResult = NonNullable<Awaited<ReturnType<typeof updateEducation>>>
    export type UpdateEducationMutationBody = UpdateEducationRequest
    export type UpdateEducationMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Update Education
 */
export const useUpdateEducation = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEducation>>, TError,{educationId: number;data: UpdateEducationRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateEducation>>,
        TError,
        {educationId: number;data: UpdateEducationRequest},
        TContext
      > => {

      const mutationOptions = getUpdateEducationMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Delete Education
 */
export const deleteEducation = (
    educationId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.delete(
      `/profiles/educations/${educationId}`,options
    );
  }



export const getDeleteEducationMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEducation>>, TError,{educationId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteEducation>>, TError,{educationId: number}, TContext> => {

const mutationKey = ['deleteEducation'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEducation>>, {educationId: number}> = (props) => {
          const {educationId} = props ?? {};

          return  deleteEducation(educationId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteEducationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEducation>>>
    
    export type DeleteEducationMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Delete Education
 */
export const useDeleteEducation = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEducation>>, TError,{educationId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteEducation>>,
        TError,
        {educationId: number},
        TContext
      > => {

      const mutationOptions = getDeleteEducationMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Add Project
 */
export const addProject = (
    createProjectRequest: CreateProjectRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileProjectDTO>> => {
    
    
    return axios.default.post(
      `/profiles/projects`,
      createProjectRequest,options
    );
  }



export const getAddProjectMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addProject>>, TError,{data: CreateProjectRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addProject>>, TError,{data: CreateProjectRequest}, TContext> => {

const mutationKey = ['addProject'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addProject>>, {data: CreateProjectRequest}> = (props) => {
          const {data} = props ?? {};

          return  addProject(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddProjectMutationResult = NonNullable<Awaited<ReturnType<typeof addProject>>>
    export type AddProjectMutationBody = CreateProjectRequest
    export type AddProjectMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Add Project
 */
export const useAddProject = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addProject>>, TError,{data: CreateProjectRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addProject>>,
        TError,
        {data: CreateProjectRequest},
        TContext
      > => {

      const mutationOptions = getAddProjectMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Update Project
 */
export const updateProject = (
    projectId: number,
    updateProjectRequest: UpdateProjectRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileProjectDTO>> => {
    
    
    return axios.default.patch(
      `/profiles/projects/${projectId}`,
      updateProjectRequest,options
    );
  }



export const getUpdateProjectMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{projectId: number;data: UpdateProjectRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{projectId: number;data: UpdateProjectRequest}, TContext> => {

const mutationKey = ['updateProject'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProject>>, {projectId: number;data: UpdateProjectRequest}> = (props) => {
          const {projectId,data} = props ?? {};

          return  updateProject(projectId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof updateProject>>>
    export type UpdateProjectMutationBody = UpdateProjectRequest
    export type UpdateProjectMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Update Project
 */
export const useUpdateProject = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{projectId: number;data: UpdateProjectRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProject>>,
        TError,
        {projectId: number;data: UpdateProjectRequest},
        TContext
      > => {

      const mutationOptions = getUpdateProjectMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Delete Project
 */
export const deleteProject = (
    projectId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.delete(
      `/profiles/projects/${projectId}`,options
    );
  }



export const getDeleteProjectMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{projectId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{projectId: number}, TContext> => {

const mutationKey = ['deleteProject'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProject>>, {projectId: number}> = (props) => {
          const {projectId} = props ?? {};

          return  deleteProject(projectId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProjectMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProject>>>
    
    export type DeleteProjectMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Delete Project
 */
export const useDeleteProject = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{projectId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProject>>,
        TError,
        {projectId: number},
        TContext
      > => {

      const mutationOptions = getDeleteProjectMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Add Skill
 */
export const addSkill = (
    createSkillRequest: CreateSkillRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileSkillDTO>> => {
    
    
    return axios.default.post(
      `/profiles/skills`,
      createSkillRequest,options
    );
  }



export const getAddSkillMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addSkill>>, TError,{data: CreateSkillRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addSkill>>, TError,{data: CreateSkillRequest}, TContext> => {

const mutationKey = ['addSkill'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addSkill>>, {data: CreateSkillRequest}> = (props) => {
          const {data} = props ?? {};

          return  addSkill(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddSkillMutationResult = NonNullable<Awaited<ReturnType<typeof addSkill>>>
    export type AddSkillMutationBody = CreateSkillRequest
    export type AddSkillMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Add Skill
 */
export const useAddSkill = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addSkill>>, TError,{data: CreateSkillRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addSkill>>,
        TError,
        {data: CreateSkillRequest},
        TContext
      > => {

      const mutationOptions = getAddSkillMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Update Skill
 */
export const updateSkill = (
    skillId: number,
    updateSkillRequest: UpdateSkillRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileSkillDTO>> => {
    
    
    return axios.default.patch(
      `/profiles/skills/${skillId}`,
      updateSkillRequest,options
    );
  }



export const getUpdateSkillMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSkill>>, TError,{skillId: number;data: UpdateSkillRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateSkill>>, TError,{skillId: number;data: UpdateSkillRequest}, TContext> => {

const mutationKey = ['updateSkill'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSkill>>, {skillId: number;data: UpdateSkillRequest}> = (props) => {
          const {skillId,data} = props ?? {};

          return  updateSkill(skillId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSkillMutationResult = NonNullable<Awaited<ReturnType<typeof updateSkill>>>
    export type UpdateSkillMutationBody = UpdateSkillRequest
    export type UpdateSkillMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Update Skill
 */
export const useUpdateSkill = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSkill>>, TError,{skillId: number;data: UpdateSkillRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSkill>>,
        TError,
        {skillId: number;data: UpdateSkillRequest},
        TContext
      > => {

      const mutationOptions = getUpdateSkillMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Delete Skill
 */
export const deleteSkill = (
    skillId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.delete(
      `/profiles/skills/${skillId}`,options
    );
  }



export const getDeleteSkillMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSkill>>, TError,{skillId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSkill>>, TError,{skillId: number}, TContext> => {

const mutationKey = ['deleteSkill'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSkill>>, {skillId: number}> = (props) => {
          const {skillId} = props ?? {};

          return  deleteSkill(skillId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteSkillMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSkill>>>
    
    export type DeleteSkillMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Delete Skill
 */
export const useDeleteSkill = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSkill>>, TError,{skillId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSkill>>,
        TError,
        {skillId: number},
        TContext
      > => {

      const mutationOptions = getDeleteSkillMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Add Certification
 */
export const addCertification = (
    createCertificationRequest: CreateCertificationRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileCertificationDTO>> => {
    
    
    return axios.default.post(
      `/profiles/certifications`,
      createCertificationRequest,options
    );
  }



export const getAddCertificationMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCertification>>, TError,{data: CreateCertificationRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addCertification>>, TError,{data: CreateCertificationRequest}, TContext> => {

const mutationKey = ['addCertification'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addCertification>>, {data: CreateCertificationRequest}> = (props) => {
          const {data} = props ?? {};

          return  addCertification(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddCertificationMutationResult = NonNullable<Awaited<ReturnType<typeof addCertification>>>
    export type AddCertificationMutationBody = CreateCertificationRequest
    export type AddCertificationMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Add Certification
 */
export const useAddCertification = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCertification>>, TError,{data: CreateCertificationRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addCertification>>,
        TError,
        {data: CreateCertificationRequest},
        TContext
      > => {

      const mutationOptions = getAddCertificationMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Update Certification
 */
export const updateCertification = (
    certificationId: number,
    updateCertificationRequest: UpdateCertificationRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileCertificationDTO>> => {
    
    
    return axios.default.patch(
      `/profiles/certifications/${certificationId}`,
      updateCertificationRequest,options
    );
  }



export const getUpdateCertificationMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCertification>>, TError,{certificationId: number;data: UpdateCertificationRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateCertification>>, TError,{certificationId: number;data: UpdateCertificationRequest}, TContext> => {

const mutationKey = ['updateCertification'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCertification>>, {certificationId: number;data: UpdateCertificationRequest}> = (props) => {
          const {certificationId,data} = props ?? {};

          return  updateCertification(certificationId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCertificationMutationResult = NonNullable<Awaited<ReturnType<typeof updateCertification>>>
    export type UpdateCertificationMutationBody = UpdateCertificationRequest
    export type UpdateCertificationMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Update Certification
 */
export const useUpdateCertification = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCertification>>, TError,{certificationId: number;data: UpdateCertificationRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCertification>>,
        TError,
        {certificationId: number;data: UpdateCertificationRequest},
        TContext
      > => {

      const mutationOptions = getUpdateCertificationMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Delete Certification
 */
export const deleteCertification = (
    certificationId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.delete(
      `/profiles/certifications/${certificationId}`,options
    );
  }



export const getDeleteCertificationMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCertification>>, TError,{certificationId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCertification>>, TError,{certificationId: number}, TContext> => {

const mutationKey = ['deleteCertification'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCertification>>, {certificationId: number}> = (props) => {
          const {certificationId} = props ?? {};

          return  deleteCertification(certificationId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCertificationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCertification>>>
    
    export type DeleteCertificationMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Delete Certification
 */
export const useDeleteCertification = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCertification>>, TError,{certificationId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCertification>>,
        TError,
        {certificationId: number},
        TContext
      > => {

      const mutationOptions = getDeleteCertificationMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Add Link
 */
export const addLink = (
    createLinkRequest: CreateLinkRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileLinkDTO>> => {
    
    
    return axios.default.post(
      `/profiles/links`,
      createLinkRequest,options
    );
  }



export const getAddLinkMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addLink>>, TError,{data: CreateLinkRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addLink>>, TError,{data: CreateLinkRequest}, TContext> => {

const mutationKey = ['addLink'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addLink>>, {data: CreateLinkRequest}> = (props) => {
          const {data} = props ?? {};

          return  addLink(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddLinkMutationResult = NonNullable<Awaited<ReturnType<typeof addLink>>>
    export type AddLinkMutationBody = CreateLinkRequest
    export type AddLinkMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Add Link
 */
export const useAddLink = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addLink>>, TError,{data: CreateLinkRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addLink>>,
        TError,
        {data: CreateLinkRequest},
        TContext
      > => {

      const mutationOptions = getAddLinkMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Update Link
 */
export const updateLink = (
    linkId: number,
    updateLinkRequest: UpdateLinkRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileLinkDTO>> => {
    
    
    return axios.default.patch(
      `/profiles/links/${linkId}`,
      updateLinkRequest,options
    );
  }



export const getUpdateLinkMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLink>>, TError,{linkId: number;data: UpdateLinkRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateLink>>, TError,{linkId: number;data: UpdateLinkRequest}, TContext> => {

const mutationKey = ['updateLink'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLink>>, {linkId: number;data: UpdateLinkRequest}> = (props) => {
          const {linkId,data} = props ?? {};

          return  updateLink(linkId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateLinkMutationResult = NonNullable<Awaited<ReturnType<typeof updateLink>>>
    export type UpdateLinkMutationBody = UpdateLinkRequest
    export type UpdateLinkMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Update Link
 */
export const useUpdateLink = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLink>>, TError,{linkId: number;data: UpdateLinkRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLink>>,
        TError,
        {linkId: number;data: UpdateLinkRequest},
        TContext
      > => {

      const mutationOptions = getUpdateLinkMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Delete Link
 */
export const deleteLink = (
    linkId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.delete(
      `/profiles/links/${linkId}`,options
    );
  }



export const getDeleteLinkMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLink>>, TError,{linkId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteLink>>, TError,{linkId: number}, TContext> => {

const mutationKey = ['deleteLink'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteLink>>, {linkId: number}> = (props) => {
          const {linkId} = props ?? {};

          return  deleteLink(linkId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteLinkMutationResult = NonNullable<Awaited<ReturnType<typeof deleteLink>>>
    
    export type DeleteLinkMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Delete Link
 */
export const useDeleteLink = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLink>>, TError,{linkId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteLink>>,
        TError,
        {linkId: number},
        TContext
      > => {

      const mutationOptions = getDeleteLinkMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    