/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CreateJobApplicationRequest,
  HTTPValidationError,
  JobApplicationDTO
} from '.././models';

import { customAxios } from '.././custom-axios';




/**
 * @summary Apply Job
 */
export const applyJobJobApplicationsPost = (
    createJobApplicationRequest: CreateJobApplicationRequest,
 signal?: AbortSignal
) => {
      
      
      return customAxios<JobApplicationDTO>(
      {url: `/job-applications/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createJobApplicationRequest, signal
    },
      );
    }
  


export const getApplyJobJobApplicationsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applyJobJobApplicationsPost>>, TError,{data: CreateJobApplicationRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof applyJobJobApplicationsPost>>, TError,{data: CreateJobApplicationRequest}, TContext> => {

const mutationKey = ['applyJobJobApplicationsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof applyJobJobApplicationsPost>>, {data: CreateJobApplicationRequest}> = (props) => {
          const {data} = props ?? {};

          return  applyJobJobApplicationsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApplyJobJobApplicationsPostMutationResult = NonNullable<Awaited<ReturnType<typeof applyJobJobApplicationsPost>>>
    export type ApplyJobJobApplicationsPostMutationBody = CreateJobApplicationRequest
    export type ApplyJobJobApplicationsPostMutationError = HTTPValidationError

    /**
 * @summary Apply Job
 */
export const useApplyJobJobApplicationsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof applyJobJobApplicationsPost>>, TError,{data: CreateJobApplicationRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof applyJobJobApplicationsPost>>,
        TError,
        {data: CreateJobApplicationRequest},
        TContext
      > => {

      const mutationOptions = getApplyJobJobApplicationsPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    