/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateJobRequest,
  ErrorModel,
  HTTPValidationError,
  JobListingDTO,
  ScrapeJobListingRequest
} from '.././models';





/**
 * @summary Scrape Job
 */
export const createJobFromUrl = (
    scrapeJobListingRequest: ScrapeJobListingRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<JobListingDTO>> => {
    
    
    return axios.default.post(
      `/job-listings/from-url`,
      scrapeJobListingRequest,options
    );
  }



export const getCreateJobFromUrlMutationOptions = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJobFromUrl>>, TError,{data: ScrapeJobListingRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createJobFromUrl>>, TError,{data: ScrapeJobListingRequest}, TContext> => {

const mutationKey = ['createJobFromUrl'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createJobFromUrl>>, {data: ScrapeJobListingRequest}> = (props) => {
          const {data} = props ?? {};

          return  createJobFromUrl(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateJobFromUrlMutationResult = NonNullable<Awaited<ReturnType<typeof createJobFromUrl>>>
    export type CreateJobFromUrlMutationBody = ScrapeJobListingRequest
    export type CreateJobFromUrlMutationError = AxiosError<ErrorModel | HTTPValidationError>

    /**
 * @summary Scrape Job
 */
export const useCreateJobFromUrl = <TError = AxiosError<ErrorModel | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJobFromUrl>>, TError,{data: ScrapeJobListingRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createJobFromUrl>>,
        TError,
        {data: ScrapeJobListingRequest},
        TContext
      > => {

      const mutationOptions = getCreateJobFromUrlMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Create Job Manual
 */
export const createJobManual = (
    createJobRequest: CreateJobRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<JobListingDTO>> => {
    
    
    return axios.default.post(
      `/job-listings/`,
      createJobRequest,options
    );
  }



export const getCreateJobManualMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJobManual>>, TError,{data: CreateJobRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createJobManual>>, TError,{data: CreateJobRequest}, TContext> => {

const mutationKey = ['createJobManual'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createJobManual>>, {data: CreateJobRequest}> = (props) => {
          const {data} = props ?? {};

          return  createJobManual(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateJobManualMutationResult = NonNullable<Awaited<ReturnType<typeof createJobManual>>>
    export type CreateJobManualMutationBody = CreateJobRequest
    export type CreateJobManualMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Create Job Manual
 */
export const useCreateJobManual = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJobManual>>, TError,{data: CreateJobRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createJobManual>>,
        TError,
        {data: CreateJobRequest},
        TContext
      > => {

      const mutationOptions = getCreateJobManualMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    