/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddOrUpdateSocialRequest,
  CandidateDTO,
  CandidateSocialLinkDTO,
  HTTPValidationError
} from '.././models';

import { customAxios } from '.././custom-axios';




/**
 * @summary Get Me
 */
export const getMeMeGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customAxios<CandidateDTO>(
      {url: `/me/`, method: 'GET', signal
    },
      );
    }
  

export const getGetMeMeGetQueryKey = () => {
    return [`/me/`] as const;
    }

    
export const getGetMeMeGetQueryOptions = <TData = Awaited<ReturnType<typeof getMeMeGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeMeGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeMeGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeMeGet>>> = ({ signal }) => getMeMeGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMeMeGet>>>
export type GetMeMeGetQueryError = unknown


export function useGetMeMeGet<TData = Awaited<ReturnType<typeof getMeMeGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeMeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeMeGet>>,
          TError,
          Awaited<ReturnType<typeof getMeMeGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeMeGet<TData = Awaited<ReturnType<typeof getMeMeGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeMeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeMeGet>>,
          TError,
          Awaited<ReturnType<typeof getMeMeGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeMeGet<TData = Awaited<ReturnType<typeof getMeMeGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeMeGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Me
 */

export function useGetMeMeGet<TData = Awaited<ReturnType<typeof getMeMeGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeMeGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeMeGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Add Social Link
 */
export const addSocialLinkMeSocialsPut = (
    addOrUpdateSocialRequest: AddOrUpdateSocialRequest,
 ) => {
      
      
      return customAxios<CandidateSocialLinkDTO>(
      {url: `/me/socials`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: addOrUpdateSocialRequest
    },
      );
    }
  


export const getAddSocialLinkMeSocialsPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addSocialLinkMeSocialsPut>>, TError,{data: AddOrUpdateSocialRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addSocialLinkMeSocialsPut>>, TError,{data: AddOrUpdateSocialRequest}, TContext> => {

const mutationKey = ['addSocialLinkMeSocialsPut'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addSocialLinkMeSocialsPut>>, {data: AddOrUpdateSocialRequest}> = (props) => {
          const {data} = props ?? {};

          return  addSocialLinkMeSocialsPut(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddSocialLinkMeSocialsPutMutationResult = NonNullable<Awaited<ReturnType<typeof addSocialLinkMeSocialsPut>>>
    export type AddSocialLinkMeSocialsPutMutationBody = AddOrUpdateSocialRequest
    export type AddSocialLinkMeSocialsPutMutationError = HTTPValidationError

    /**
 * @summary Add Social Link
 */
export const useAddSocialLinkMeSocialsPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addSocialLinkMeSocialsPut>>, TError,{data: AddOrUpdateSocialRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addSocialLinkMeSocialsPut>>,
        TError,
        {data: AddOrUpdateSocialRequest},
        TContext
      > => {

      const mutationOptions = getAddSocialLinkMeSocialsPutMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Remove Social Link
 */
export const removeSocialLinkMeSocialsSocialIdDelete = (
    socialId: number,
 ) => {
      
      
      return customAxios<unknown>(
      {url: `/me/socials/${socialId}`, method: 'DELETE'
    },
      );
    }
  


export const getRemoveSocialLinkMeSocialsSocialIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeSocialLinkMeSocialsSocialIdDelete>>, TError,{socialId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof removeSocialLinkMeSocialsSocialIdDelete>>, TError,{socialId: number}, TContext> => {

const mutationKey = ['removeSocialLinkMeSocialsSocialIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeSocialLinkMeSocialsSocialIdDelete>>, {socialId: number}> = (props) => {
          const {socialId} = props ?? {};

          return  removeSocialLinkMeSocialsSocialIdDelete(socialId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveSocialLinkMeSocialsSocialIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof removeSocialLinkMeSocialsSocialIdDelete>>>
    
    export type RemoveSocialLinkMeSocialsSocialIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Remove Social Link
 */
export const useRemoveSocialLinkMeSocialsSocialIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeSocialLinkMeSocialsSocialIdDelete>>, TError,{socialId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeSocialLinkMeSocialsSocialIdDelete>>,
        TError,
        {socialId: number},
        TContext
      > => {

      const mutationOptions = getRemoveSocialLinkMeSocialsSocialIdDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    