/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface CreateCandidateRequest {
  first_name: string;
  last_name: string;
  email: string;
  password: string;
}
