/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CreateJobApplicationRequestCoverLetterId } from './createJobApplicationRequestCoverLetterId';

export interface CreateJobApplicationRequest {
  job_listing_id: number;
  resume_id: number;
  cover_letter_id?: CreateJobApplicationRequestCoverLetterId;
}
