/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CoverLetterDTO } from './coverLetterDTO';

export type JobApplicationDTOUsedCoverLetter = CoverLetterDTO | null;
