/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProfileDTOContactPhone } from './profileDTOContactPhone';
import type { ProfileDTOWorkLocation } from './profileDTOWorkLocation';
import type { ProfileDTOSummary } from './profileDTOSummary';
import type { ProfileExperienceDTO } from './profileExperienceDTO';
import type { ProfileEducationDTO } from './profileEducationDTO';
import type { ProfileProjectDTO } from './profileProjectDTO';
import type { ProfileSkillDTO } from './profileSkillDTO';
import type { ProfileCertificationDTO } from './profileCertificationDTO';
import type { ProfileLinkDTO } from './profileLinkDTO';

export interface ProfileDTO {
  id: number;
  first_name: string;
  last_name: string;
  contact_email: string;
  contact_phone: ProfileDTOContactPhone;
  work_location: ProfileDTOWorkLocation;
  summary: ProfileDTOSummary;
  created_at: string;
  updated_at: string;
  experiences?: ProfileExperienceDTO[];
  educations?: ProfileEducationDTO[];
  projects?: ProfileProjectDTO[];
  skills?: ProfileSkillDTO[];
  certifications?: ProfileCertificationDTO[];
  links?: ProfileLinkDTO[];
}
