/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { StoredFileDTOContentType } from './storedFileDTOContentType';
import type { StoredFileDTOKey } from './storedFileDTOKey';

export interface StoredFileDTO {
  id: number;
  uploaded_at: string;
  content_type: StoredFileDTOContentType;
  key: StoredFileDTOKey;
}
