/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateProfileRequestFirstName } from './updateProfileRequestFirstName';
import type { UpdateProfileRequestLastName } from './updateProfileRequestLastName';
import type { UpdateProfileRequestContactEmail } from './updateProfileRequestContactEmail';
import type { UpdateProfileRequestContactPhone } from './updateProfileRequestContactPhone';
import type { UpdateProfileRequestWorkLocation } from './updateProfileRequestWorkLocation';
import type { UpdateProfileRequestSummary } from './updateProfileRequestSummary';

export interface UpdateProfileRequest {
  first_name?: UpdateProfileRequestFirstName;
  last_name?: UpdateProfileRequestLastName;
  contact_email?: UpdateProfileRequestContactEmail;
  contact_phone?: UpdateProfileRequestContactPhone;
  work_location?: UpdateProfileRequestWorkLocation;
  summary?: UpdateProfileRequestSummary;
}
